database:
  username: whdjoixntqhpor
  host: ec2-52-3-200-138.compute-1.amazonaws.com
  port: 5432
  password: e13641e014ab0837ce00d6cbdbcb0f404466eb9bc1156257175cb396b7e1e9ac
  name: dfe9nvf1s0o5pr
application:
  port: 8080
secretkey: "hello-world"